resources:
- ../ghost.yaml
patchesStrategicMerge:
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ghost
      labels:
        nirmata.io/deployment.name: "ghost"
        nirmata.io/component: "ghost"
    spec:
      replicas: 3       